name: Build app

on: [push]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        configuration: [Release]
        selfcontained: [false, true]
        singlefile: [false, true]
        include:
          - os: ubuntu-latest
            rid: linux-x64
          - os: windows-latest
            rid: win-x64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build FunManipulator --no-restore
    - name: Publish ${{ matrix.os }}-${{ matrix.configuration }}-selfcontained-${{ matrix.selfcontained }}-singlefile-${{ matrix.singlefile }}
      run: dotnet publish FunManipulator -c ${{ matrix.configuration }} -r ${{ matrix.rid }} --self-contained ${{ matrix.selfcontained }} -p:PublishSingleFile=${{ matrix.singlefile }} --output app_${{ matrix.rid }}-${{ matrix.configuration }}-selfcontained-${{ matrix.selfcontained }}-singlefile-${{ matrix.singlefile }}
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: FunManipulator_${{ matrix.rid }}-${{ matrix.configuration }}-selfcontained-${{ matrix.selfcontained }}-singlefile-${{ matrix.singlefile }}
        path: app_${{ matrix.rid }}-${{ matrix.configuration }}-selfcontained-${{ matrix.selfcontained }}-singlefile-${{ matrix.singlefile }}
        
